# Generated by Django 3.2.25 on 2025-01-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='post/images'),
            preserve_default=False,
        ),
    ]
