# Generated by Django 3.2.25 on 2025-01-13 12:41

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to=post.models.get_image_upload_path),
        ),
    ]
