# Generated by Django 5.1.2 on 2025-02-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Breweries',
                'db_table': 'breweries',
            },
        ),
        migrations.CreateModel(
            name='TopLiquor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('characteristics', models.JSONField()),
                ('rank', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'top_liquors',
            },
        ),
        migrations.CreateModel(
            name='TraditionalLiquor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('characteristics', models.JSONField()),
                ('alcohol_percentage', models.FloatField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquors', to='liquor.brewery')),
            ],
            options={
                'db_table': 'traditional_liquors',
            },
        ),
        migrations.CreateModel(
            name='SimilarLiquor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('similarity_factors', models.JSONField()),
                ('similar_liquor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='liquor.topliquor')),
                ('liquor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='liquor.traditionalliquor')),
            ],
            options={
                'db_table': 'similar_liquors',
            },
        ),
        migrations.CreateModel(
            name='LiquorIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('description', models.TextField()),
                ('liquor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='liquor.traditionalliquor')),
            ],
            options={
                'db_table': 'liquor_ingredients',
            },
        ),
    ]
