# Generated by Django 5.1.2 on 2025-02-21 02:22

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=20), blank=True, null=True, size=None)),
                ('userID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, null=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=20), blank=True, null=True, size=None)),
                ('recentChats', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, null=True, size=None)),
                ('prefor', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, null=True, size=None)),
                ('characterstics', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('additionalInfo', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
