# Generated by Django 5.1.2 on 2025-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_voicevector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accountID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
