# Generated by Django 5.1.2 on 2025-02-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imageUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
