# Generated by Django 5.1.2 on 2025-02-26 09:23

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('userID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imageUrl', models.TextField(blank=True, null=True)),
                ('characteristics', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'character',
            },
        ),
    ]
