# Generated by Django 5.1.2 on 2025-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='userID',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
